# Generated by Django 3.0.3 on 2021-06-27 00:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('systems', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('memo', models.TextField(blank=True, verbose_name='備註')),
                ('field_attribute', models.BooleanField(default=False, verbose_name='字段是否內置')),
                ('field_type', models.CharField(choices=[(1, '字符串'), (2, '整型'), (3, '浮點型'), (4, '布爾'), (5, '日期'), (6, '日期時間'), (7, '範圍日期'), (8, '文本域'), (9, '單選框'), (10, '下拉列表'), (11, '用戶名'), (12, '多選框'), (13, '多選下拉'), (14, '多選用戶名')], default=0, max_length=1, verbose_name='字段類型')),
                ('field_key', models.CharField(help_text='字段類型請儘量特殊，避免與系統中關鍵字衝突', max_length=50, verbose_name='字段標識')),
                ('field_name', models.CharField(max_length=50, verbose_name='字段名稱')),
                ('order_id', models.IntegerField(default=0, verbose_name='排序')),
                ('default_value', models.CharField(blank=True, help_text='前端展示時，可以將此內容作為表單中的該字段的默認值', max_length=100, null=True, verbose_name='默認值')),
                ('field_template', models.TextField(blank=True, default='', help_text='文本域類型字段前端顯示時可以將此內容作為字段的placeholder', verbose_name='文本域模板')),
                ('boolean_field_display', models.CharField(blank=True, default='{}', help_text='當為布爾類型時候，可以支持自定義顯示形式。{"1":"是","0":"否"}或{"1":"需要","0":"不需要"}，注意數字也需要引號', max_length=100, verbose_name='布爾類型顯示名')),
                ('field_choice', models.CharField(blank=True, default='{}', help_text='radio,checkbox,select,multiselect類型可供選擇的選項，格式為json如:{"1":"中國", "2":"美國"},注意數字也需要引號', max_length=255, verbose_name='radio、checkbox、select的選項')),
                ('label', models.CharField(blank=True, default='{}', help_text='自定義標籤，json格式，調用方可根據標籤自行處理特殊場景邏輯，loonflow只保存文本內容', max_length=100, verbose_name='標籤')),
            ],
            options={
                'verbose_name': '工作流自定義字段',
                'verbose_name_plural': '工作流自定義字段',
                'ordering': ['order_id'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('memo', models.TextField(blank=True, verbose_name='備註')),
                ('name', models.CharField(max_length=50, verbose_name='名稱')),
                ('is_hidden', models.BooleanField(default=False, help_text='設置為True時,獲取工單步驟api中不顯示此狀態(當前處於此狀態時除外)', verbose_name='是否隱藏')),
                ('order_id', models.IntegerField(default=1, verbose_name='狀態順序')),
                ('state_type', models.CharField(choices=[(0, '普通狀態'), (1, '初始狀態'), (2, '結束狀態')], default=0, max_length=1, verbose_name='狀態類型')),
                ('enable_retreat', models.BooleanField(default=False, help_text='開啟後允許工單創建人在此狀態直接撤回工單到初始狀態', verbose_name='允許撤回')),
                ('participant_type', models.CharField(choices=[('none', '無處理人'), ('user', '個人'), ('group', '部門'), ('role', '角色')], default='none', max_length=5, verbose_name='參與者類型')),
                ('fields', models.ManyToManyField(blank=True, to='workflows.CustomField', verbose_name='可編輯字段')),
                ('group_participant', models.ManyToManyField(blank=True, to='systems.Group', verbose_name='參與組')),
                ('role_participant', models.ManyToManyField(blank=True, to='systems.Role', verbose_name='參與角色')),
                ('user_participant', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='參與用戶')),
            ],
            options={
                'verbose_name': '工作流狀態',
                'verbose_name_plural': '工作流狀態',
                'ordering': ['order_id'],
            },
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('memo', models.TextField(blank=True, verbose_name='備註')),
                ('name', models.CharField(max_length=50, verbose_name='名稱')),
                ('key', models.CharField(blank=True, max_length=168, verbose_name='流程標識key')),
                ('ticket_sn_prefix', models.CharField(default='xxoo', max_length=20, verbose_name='工單流水號前綴')),
                ('status', models.BooleanField(default=True)),
                ('view_permission_check', models.BooleanField(default=True, help_text='開啟後，只允許工單的關聯人(創建人、曾經的處理人)有權限查看工單', verbose_name='查看權限校驗')),
                ('limit_expression', models.TextField(blank=True, default='{}', help_text='限制週期({"period":24} 24小時), 限制次數({"count":1}在限制週期內只允許提交1次), 限制級別({"level":1} 針對(1單個用戶 2全局)限制週期限制次數,默認特定用戶);允許特定人員提交({"allow_persons":"zhangsan,lisi"}只允許張三提交工單,{"allow_depts":"1,2"}只允許部門id為1和2的用戶提交工單，{"allow_roles":"1,2"}只允許角色id為1和2的用戶提交工單)', verbose_name='限制表達式')),
                ('display_form_str', models.TextField(blank=True, default='[]', help_text='默認"[]"，用於用戶只有對應工單查看權限時顯示哪些字段,field_key的list的json,如["days","sn"],內置特殊字段participant_info.participant_name:當前處理人信息(部門名稱、角色名稱)，state.state_name:當前狀態的狀態名,workflow.workflow_name:工作流名稱', verbose_name='展現表單字段')),
                ('title_template', models.CharField(blank=True, default='你有一個待辦工單:{title}', help_text='工單字段的值可以作為參數寫到模板中，格式如：你有一個待辦工單:{title}', max_length=50, null=True, verbose_name='標題模板')),
                ('roles', models.ManyToManyField(blank=True, related_name='workflow_set', related_query_name='workflow', to='systems.Role', verbose_name='關聯角色')),
            ],
            options={
                'verbose_name': '工作流',
                'verbose_name_plural': '工作流',
            },
        ),
        migrations.CreateModel(
            name='WorkflowType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('memo', models.TextField(blank=True, verbose_name='備註')),
                ('name', models.CharField(max_length=50, verbose_name='名稱')),
                ('status', models.BooleanField(default=True)),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='代碼')),
                ('order_id', models.IntegerField(default=1, verbose_name='狀態順序')),
            ],
            options={
                'verbose_name': '工作流類型',
                'verbose_name_plural': '工作流類型',
                'ordering': ['order_id'],
            },
        ),
        migrations.CreateModel(
            name='WorkflowBpmn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('memo', models.TextField(blank=True, verbose_name='備註')),
                ('xml', models.TextField(blank=True, verbose_name='xml數據')),
                ('svg', models.TextField(blank=True, verbose_name='svg數據')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.Workflow', verbose_name='工作流')),
            ],
            options={
                'verbose_name': '工作流bpmn',
                'verbose_name_plural': '工作流bpmn',
            },
        ),
        migrations.AddField(
            model_name='workflow',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.WorkflowType', verbose_name='工作流類型'),
        ),
        migrations.CreateModel(
            name='Transition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='創建時間')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('memo', models.TextField(blank=True, verbose_name='備註')),
                ('name', models.CharField(choices=[(0, '保存'), (1, '轉交下一步'), (2, '駁回'), (3, '撤銷'), (4, '關閉')], default=1, max_length=1, verbose_name='名稱類型')),
                ('transition_type', models.CharField(choices=[(0, '常規流轉'), (1, '定時器流轉')], default=0, max_length=1, verbose_name='流轉類型')),
                ('timer', models.IntegerField(default=0, help_text='流轉類型設置為定時器流轉時生效,單位秒。處於源狀態X秒後如果狀態都沒有過變化則自動流轉到目標狀態', verbose_name='定時器(單位秒)')),
                ('condition_expression', models.TextField(default='[]', help_text='流轉條件表達式，根據表達式中的條件來確定流轉的下個狀態，格式為[{"expression":"{days} > 3 and {days}<10", "target_state_id":11}] 其中{}用於填充工單的字段key,運算時會換算成實際的值，當符合條件下個狀態將變為target_state_id中的值,表達式只支持簡單的運算或datetime/time運算.loonflow會以首次匹配成功的條件為準，所以多個條件不要有衝突', verbose_name='條件表達式')),
                ('attribute_type', models.CharField(choices=[(0, '草稿'), (1, '待審'), (2, '駁回'), (3, '撤銷'), (4, '結束'), (5, '已關閉')], default=0, max_length=1, verbose_name='屬性類型')),
                ('alert_enable', models.BooleanField(default=False, verbose_name='點擊彈窗提示')),
                ('alert_text', models.CharField(blank=True, default='', max_length=100, verbose_name='彈窗內容')),
                ('dest_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dest_state', to='workflows.State', verbose_name='目的狀態')),
                ('source_state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_state', to='workflows.State', verbose_name='源狀態')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.Workflow', verbose_name='工作流')),
            ],
            options={
                'verbose_name': '工作流流轉',
                'verbose_name_plural': '工作流流轉',
            },
        ),
        migrations.AddField(
            model_name='state',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.Workflow', verbose_name='工作流'),
        ),
        migrations.AddField(
            model_name='customfield',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.Workflow', verbose_name='工作流'),
        ),
    ]
